name: Deploy Supabase Edge Functions

on:
  push:
    branches: [ "main" ]
    paths:
      - "supabase/functions/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link project
        run: supabase link --project-ref ${{ secrets.PROJECT_REF }}

      # 필요 함수만 나열해서 배포합니다. 함수명이 다르면 여기만 수정하세요.
      - name: Deploy send-delete-confirm
        run: supabase functions deploy send-delete-confirm

      - name: Deploy confirm-delete
        run: supabase functions deploy confirm-delete
